export interface PayslipModel {
  id: number;
  id_pegawai: number;
  tanggal: string;
  gaji_pokok: number;
  jml_tunjangan: number;
  jml_potongan: number;
  tot_gaji_diterima: number;
  dikirim_tgl: string;
  is_sent: number;
  path: string;
  created_at: string;
  updated_at: string;
  menit_kerja: number;
  hari_kerja: number;
  telat_datang: number;
  telat_pulang: number;
  overtime_datang: string;
  overtime_pulang: string;
  telat: number;
  overtime: number;
  att_potongan: string;
  att_tunjangan: string;
  tot_pemasukan: number;
  jml_ptgn_telat: number;
  jml_ptgn_bolos: number;
  tunj_status: number;
  tunj_anak: number;
  tunj_kinerja: string | number;
  tunj_jabatan: number;
  komisi: string | number;
  tunj_makan_lembur: number;
  tunj_absensi: number;
  tunj_lain: number;
  tunj_parkir: string | number;
  tunj_transport: string | number;
  tax_allowance: string | number;
  tunj_penampilan: string | number;
  garansi_komisi: string | number;
  tunj_tempat_tinggal: string | number;
  jml_overtime: number;
  rapel_minus: string | number;
  pinjaman_karyawan: string | number;
  jp_employee: number;
  jht_employee: number;
  pph21: number;
  pph21_penalty: string | number;
  rapel_plus: string | number;
  bonus: string | number;
  severance: string | number;
  jkk_perusahaan: number;
  jp_perusahaan: number;
  jht_perusahaan: number;
  jkm_perusahaan: number;
  tot_pemotongan: number;
  tot_benefit: number;
  tot_pemasukan_kotor: number;
  total_menit_lembur: number;
  taxrate: string;
  salary_bruto: number;
  total_jam_lembur: string;
  gaji_tunjangan_menit: number;
  gaji_tunjangan_jam: number;
  gaji_tunjangan_hari: number;
  gaji_tunjangan: number;
  total_libur_nasional: number;
  total_hari_libur: number;
  total_hari_hadir_weekend: number;
  total_hari_hadir_weekday: number;
  total_hari_dinas: number;
  total_tidak_masuk_all: number;
  total_hari_kerja: number;
  bonus_susut: string | number;
  potongan_susut: string | number;
  pot_bpjs_karyawan: number;
  bpjs_perusahaan: number;
}
